global:
  scrape_interval: 5s  # how often to collect metrics
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "backend"
    static_configs:
      - targets: ["backend:3001"]
    scrape_interval: 5s
    metrics_path: /metrics  